name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build-Lib
      run: cd ./lib && cargo build --verbose
    - name: Test-Lib
      run: cd ./lib && cargo test --verbose
    - name: Build-Core
      run: cd ./core && cargo build --verbose
    - name: Test-Core
      run: cd ./core && cargo test --verbose
    - name: Build-Nodes
      run: cd ./nodes && cargo build --verbose
    - name: Test-Noes
      run: cd ./nodes && cargo test --verbose
